version: '3'
networks:
  ldap:
services:
  ldap:
    image: osixia/openldap
    ports:
      - "389:389"
      - "689:689"
    networks:
      - ldap
  phpldapadmin:
    image:  osixia/phpldapadmin
    environment:
      - "PHPLDAPADMIN_LDAP_HOSTS=ldap"
    networks:
      - ldap
    ports:
      - "6443:443"
  ldap-self-rest-service:
    image: fchristl/ldap-self-rest-service
    networks:
      - ldap
    environment:
      - "LDAP_HOST=ldap"
      - "LDAP_BIND_DN=cn=admin,dc=example,dc=org"
      - "LDAP_BIND_PASSWORD=admin"
      - "LDAP_BASE_USER_DN=cn=users,dc=example,dc=org"
      - "EDITABLE_ATTRIBUTES=sn,mobile"
    ports:
    - "8081:3000"
    depends_on:
      - ldap
  ldap-self-service:
    image: fchristl/ldap-self-service
    networks:
      - ldap
    environment:
     - "EDITABLE_FIELDS=[\"sn\", \"mobile\"]"
     - "LDAP_REST_SERVICE_ENDPOINT=http://localhost:8081"
    ports:
    - "8080:80"
    depends_on:
      - ldap-self-rest-service